  
version: "3.9"
services:

    frontend:
        container_name: wars-front
		image: node
        ports:
            - "4200:4200"
        volumes:
            - ./frontend:/usr/src/app/frontend
        command: npm run start
        working_dir: /usr/src/app/frontend
        depends_on: 
            - api

    api:
        # image: node
        container_name: wars-api
        build:
            dockerfile: backend/Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://war:war123admin@postgres:5432/warbdd
            NODE_ENV: development
            PORT: 3000
        ports:
            - "3000:3000"
        volumes:
            - ./backend:/usr/src/app/backend
        command: npm run start:debug

    postgres:
        container_name: wars-bdd
        image: postgres:13.3
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: war
            POSTGRES_PASSWORD: war123admin
            POSTGRES_DB: warbdd
