  
version: "3.9"
services:
    api:
        # image: war/app
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://war:war123admin@postgres:5432/warbdd
            NODE_ENV: development
            PORT: 3000
        ports:
            - "8080:3000"

    postgres:
        image: postgres:13.3
        ports:
            - "35000:5432"
        environment: 
            POSTGRES_USER: war
            POSTGRES_PASSWORD: war123admin
            POSTGRES_DB: warbdd